package com.example.project.service.impl;

import com.example.project.model.entity.Landmark;
import com.example.project.model.entity.Town;
import com.example.project.model.service.LandmarkServiceModel;
import com.example.project.repository.LandmarkRepository;
import com.example.project.service.LandmarkService;
import com.example.project.service.TownService;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

@Service
public class LandmarkServiceImpl implements LandmarkService {
    private final LandmarkRepository landmarkRepository;
    private final TownService townService;
    private final ModelMapper modelMapper;

    public LandmarkServiceImpl(LandmarkRepository landmarkRepository, TownService townService, ModelMapper modelMapper) {
        this.landmarkRepository = landmarkRepository;
        this.townService = townService;
        this.modelMapper = modelMapper;
    }

    @Override
    public void initialiseLandmarks() {
        if (landmarkRepository.count()==0){
            Town sofia = townService.findByName("Sofia");
            Landmark nevski = new Landmark("Saint Alexander of Neva Patriarch's Cathedral", "https://res.cloudinary.com/ivoto22/image/upload/v1635681712/aleksandarnevski_pionzm.jpg", sofia);
            nevski.setDescription("The St. Alexander Nevsky Cathedral is a Bulgarian Orthodox cathedral in Sofia, the capital of Bulgaria. Built in Neo-Byzantine style, it serves as the cathedral church of the Patriarch of Bulgaria and it is believed to be one of the 50 largest Christian church buildings by volume in the world. It is one of Sofia's symbols and primary tourist attractions. The St. Alexander Nevsky Cathedral in Sofia occupies an area of 3,170 square metres and can hold 5,000 people inside. It is believed to be among the 10 largest Eastern Orthodox church buildings. It is the largest completed Orthodox Cathedral located in Southeast Europe. It is believed that until year 2000 it was the largest finished Orthodox Cathedral.");
            landmarkRepository.save(nevski);
            Landmark palaceofculture = new Landmark("National Palace of Culture", "https://res.cloudinary.com/ivoto22/image/upload/v1635682153/licensed-image_y0977m.jpg", sofia);
            palaceofculture.setDescription("The National Palace of Culture, located in Sofia, the capital of Bulgaria, is the largest, multifunctional conference and exhibition centre in south-eastern Europe. It was opened in 1981 in celebration of Bulgaria's 1300th anniversary. The centre was initiated at the suggestion of Lyudmila Zhivkova, daughter of the communist leader of the former People's Republic of Bulgaria Todor Zhivkov. The project was designed by a team of Bulgarian and foreign architects led by Alexander Georgiev Barov along with Ivan Kanazirev. The landscaping of Bulgaria Square in front of the National Palace of Culture was designed by another team of architects and landscape engineers, led by Atanas Agura. Internally, the building exhibits a unified style, employing an octagonal motif and heavy, dark colours. Large bright murals depicting historical figures and events cover the main wall of many of the smaller halls. During the 1990s, immediately following the change of the political model in the country, the NDK lost a significant portion of its property, including infrastructure, commercial areas, and car parks.");
            landmarkRepository.save(palaceofculture);
            Landmark borisgardner = new Landmark("Boris' Garden Park", "https://res.cloudinary.com/ivoto22/image/upload/v1635682286/licensed-image_1_z9wl5j.jpg", sofia);
            borisgardner.setDescription("Borisova gradina or Knyaz-Borisova gradina is the oldest and best known park in Sofia, the capital of Bulgaria. Its construction and arrangement began in 1884 and it is named after Bulgarian Tsar Boris III. The history of the garden embraces three periods under three renowned gardeners. All followed the initial scheme, developing it further and perfecting it instead of making radical changes to the original design");
            Town belgrade = townService.findByName("Belgrade");
            Landmark belgradefortress = new Landmark("Belgrade Fortress", "https://res.cloudinary.com/ivoto22/image/upload/v1635682472/licensed-image_2_mk0jjd.jpg", belgrade);
            belgradefortress.setDescription("The Belgrade Fortress, consists of the old citadel and Kalemegdan Park on the confluence of the Sava and Danube rivers, in an urban area of modern Belgrade, Serbia. It is located in Belgrade's municipality of Stari Grad. Belgrade Fortress was declared a Monument of Culture of Exceptional Importance in 1979, and is protected by the Republic of Serbia. It is the most visited tourist attraction in Belgrade, with Skadarlija being the second. Since the admission is free, it is estimated that the total number of visitors is over 2 million yearly.");
            landmarkRepository.save(belgradefortress);
            Landmark aeronauticalmuseum = new Landmark("Aeronautical Museum", "https://res.cloudinary.com/ivoto22/image/upload/v1635682835/images_nfjbra.jpg", belgrade);
            aeronauticalmuseum.setDescription("The Aeronautical Museum Belgrade, formerly known as the Yugoslav Aeronautical Museum, is a museum located in Surčin, Belgrade, the capital of Serbia. Founded in 1957, the museum is located adjacent to Belgrade Nikola Tesla Airport. The current facility, designed by architect Ivan Štraus, was opened to the public on 21 May 1989");
            landmarkRepository.save(aeronauticalmuseum);
            Landmark noveupalasis = new Landmark("Nouveau Palais", "https://res.cloudinary.com/ivoto22/image/upload/v1635683047/2021-05-27_x0hfmx.jpg", belgrade);
            noveupalasis.setDescription("The New Palace was a royal residence of the Karađorđević dynasty of Serbia and later Kingdom of Yugoslavia. Today it is the seat of the President of Serbia. The palace is located on Andrićev Venac in Belgrade, Serbia, opposite of Stari Dvor.");
            landmarkRepository.save(noveupalasis);
            Town dubrovnik = townService.findByName("Dubrovnik");
            Landmark cablecar = new Landmark("Dubrovnik Cable Car", "https://res.cloudinary.com/ivoto22/image/upload/v1635683384/images_1_hmovam.jpg", dubrovnik);
            cablecar.setDescription("Scenic hillside ride for views & dining");
            landmarkRepository.save(cablecar);
            Landmark gameofthronestour = new Landmark("Game Of Thrones Tour", "https://res.cloudinary.com/ivoto22/image/upload/v1635683575/Game-of-Thrones-Tour-Dubrovnik_zab8el.jpg", dubrovnik);
            gameofthronestour.setDescription("Walk past landmarks from the fictional Westeros on a Game of Thrones filming locations tour.");
            landmarkRepository.save(gameofthronestour);
            Landmark stradun = new Landmark("Stradun", "https://res.cloudinary.com/ivoto22/image/upload/v1635683689/images_2_a8qm9j.jpg", dubrovnik);
            stradun.setDescription("Stradun or Placa is the main street of Dubrovnik, Croatia. The limestone-paved pedestrian street runs some 300 metres through the Old Town, the historic part of the city surrounded by the Walls of Dubrovnik. The site of the present-day street used to be a marshy channel which separated Ragusa from the forest settlement of Dubrava before it was reclaimed in the 13th century. Stradun stretches through the walled town in the east-west direction, connecting the western entrance called the \"Pile Gate\" to the \"Ploče Gate\" on the eastern end. Both ends are also marked with 15th-century fountains and bell towers. Stradun became the city's main thoroughfare in the 13th century, and its current appearance was for the most part created following the devastating 1667 earthquake in which most of the buildings in Ragusa were destroyed. Before the earthquake the houses which line the street were not so uniformly designed as they appear today, with many of them featuring arcades and elaborate decorations.");
            landmarkRepository.save(stradun);
            Town zagreb = townService.findByName("Zagreb");
            Landmark cathedralofzagreb = new Landmark("Cathedral of Zagreb", "https://res.cloudinary.com/ivoto22/image/upload/v1635683825/images_3_dtjely.jpg", zagreb);
            cathedralofzagreb.setDescription("Zagreb Cathedral, on the Kaptol, is a Roman Catholic cathedral-church and not only the second tallest building in Croatia but also the most monumental sacral building in Gothic style southeast of the Alps. It is dedicated to the Assumption of Mary and to kings Saint Stephen and Saint Ladislaus. The cathedral is typically Gothic, as is its sacristy, which is of great architectural value. Its prominent spires are considered to be landmarks as they are visible from most parts of the city. One of its two spires was damaged in an earthquake that took place on March 22nd, 2020.");
            landmarkRepository.save(cathedralofzagreb);
            Landmark medvednica = new Landmark("Medvednica", "https://res.cloudinary.com/ivoto22/image/upload/v1635684006/licensed-image_3_xu2ehc.jpg", zagreb);
            medvednica.setDescription("Medvednica is a mountain in central Croatia, just north of Zagreb, and marking the southern border of the historic region of Zagorje. The highest peak, at 1,035 m is Sljeme. Most of the area of Medvednica is a nature park, a type of preservation lesser than a national park. The area of the park is 228.26 km² and about 63% is covered with forest. During Miocene and Pliocene, the mountain was an island within the Pannonian Sea. ");
            landmarkRepository.save(medvednica);
            Town ljubljana = townService.findByName("Ljubljana");
            Landmark dragonbridge = new Landmark("Dragon Bridge", "https://res.cloudinary.com/ivoto22/image/upload/v1635684226/licensed-image_4_mdcyk2.jpg", ljubljana);
            dragonbridge.setDescription("The Dragon Bridge is a road bridge located in Ljubljana, the capital of Slovenia. It crosses the Ljubljanica River. between Kopitar Street and Ressel Street, to the north of the Ljubljana Central Market at Vodnik Square. It was built in the beginning of the 20th century, when Ljubljana was part of the Austro-Hungarian Empire. As one of the best examples of reinforced concrete bridges and of the Vienna Secession style, the bridge is today protected as a technical monument. It is intended primarily for motorised traffic.");
            landmarkRepository.save(dragonbridge);
            Landmark ljubljanacastle = new Landmark("Ljubljana Castle", "https://res.cloudinary.com/ivoto22/image/upload/v1635684331/licensed-image_5_nqfqnh.jpg", ljubljana);
            ljubljanacastle.setDescription("Ljubljana Castle is a castle complex standing on Castle Hill above downtown Ljubljana, the capital of Slovenia. It is a key landmark of the town. Originally a medieval fortress, it was probably constructed in the 11th century and rebuilt in the 12th century. It acquired its present outline with an almost complete overhaul in the 15th century, whereas the majority of the buildings date to the 16th and 17th centuries. Initially a defense structure and since the first half of the 14th century the seat of the lords of Carniola, it was since the early 19th century used for various other purposes and today is used as a major cultural venue. The castle is depicted on the city's coat of arms, along with a dragon on top.");
            landmarkRepository.save(ljubljanacastle);
            Town rome = townService.findByName("Rome");
            Landmark colloseum = new Landmark("Colosseum", "https://res.cloudinary.com/ivoto22/image/upload/v1635684459/images_4_rdvkxp.jpg", rome);
            colloseum.setDescription("The Colosseum is an oval amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world today, despite its age. Construction began under the emperor Vespasian in 72 and was completed in 80 AD under his successor and heir, Titus. Further modifications were made during the reign of Domitian. The three emperors that were patrons of the work are known as the Flavian dynasty, and the amphitheatre was named the Flavian Amphitheatre by later classicists and archaeologists for its association with their family name. The Colosseum is built of travertine limestone, tuff, and brick-faced concrete. The Colosseum could hold an estimated 50,000 to 80,000 spectators at various points in its history having an average audience of some 65,000; it was used for gladiatorial contests and public spectacles including animal hunts, executions, re-enactments of famous battles, and dramas based on Roman mythology, and briefly mock sea battles. The building ceased to be used for entertainment in the early medieval era.");
            landmarkRepository.save(colloseum);
            Landmark trevifountain = new Landmark("Trevi Fountain", "https://res.cloudinary.com/ivoto22/image/upload/v1635684545/images_5_zkmxot.jpg", rome);
            trevifountain.setDescription("The Trevi Fountain is a fountain in the Trevi district in Rome, Italy, designed by Italian architect Nicola Salvi and completed by Giuseppe Pannini and several others. Standing 26.3 metres high and 49.15 metres wide, it is the largest Baroque fountain in the city and one of the most famous fountains in the world. The fountain has appeared in several films, including Roman Holiday, the eponymous Three Coins in the Fountain, Federico Fellini's classic La Dolce Vita, The Lizzie McGuire Movie, and Sabrina Goes to Rome.");
            landmarkRepository.save(trevifountain);
            Landmark romancforum = new Landmark("Roman Forum","https://res.cloudinary.com/ivoto22/image/upload/v1635684636/images_6_mj1qak.jpg", rome);
            romancforum.setDescription("The Roman Forum, also known by its Latin name Forum Romanum, is a rectangular forum surrounded by the ruins of several important ancient government buildings at the center of the city of Rome. Citizens of the ancient city referred to this space, originally a marketplace, as the Forum Magnum, or simply the Forum. For centuries the Forum was the center of day-to-day life in Rome: the site of triumphal processions and elections; the venue for public speeches, criminal trials, and gladiatorial matches; and the nucleus of commercial affairs. Here statues and monuments commemorated the city's great men. The teeming heart of ancient Rome, it has been called the most celebrated meeting place in the world, and in all history. Located in the small valley between the Palatine and Capitoline Hills, the Forum today is a sprawling ruin of architectural fragments and intermittent archaeological excavations attracting 4.5 million or more sightseers yearly. Many of the oldest and most important structures of the ancient city were located on or near the Forum. The Roman Kingdom's earliest shrines and temples were located on the southeastern edge.");
            landmarkRepository.save(romancforum);
            Landmark spanishsteps = new Landmark("Spanish Steps","https://res.cloudinary.com/ivoto22/image/upload/v1635684708/images_7_apoqar.jpg", rome);
            spanishsteps.setDescription("The Spanish Steps are a set of steps in Rome, Italy, climbing a steep slope between the Piazza di Spagna at the base and Piazza Trinità dei Monti, dominated by the Trinità dei Monti church at the top. The monumental stairway of 135 steps was built with French diplomat Étienne Gueffier's bequeathed funds of 20,000 scudi, in 1723–1725, linking the Trinità dei Monti church that was under the patronage of the Bourbon kings of France and the Bourbon Spanish Embassy at the top of the steps to the Holy See in the Palazzo Monaldeschi at the bottom of the steps. The stairway was designed by architects Francesco de Sanctis and Alessandro Specchi.");
            landmarkRepository.save(spanishsteps);
            Town florence = townService.findByName("Florentia");
            Landmark basillica = new Landmark("Basilica of Santa Croce", "https://res.cloudinary.com/ivoto22/image/upload/v1635684842/licensed-image_6_bhuls5.jpg", florence);
            basillica.setDescription("The Basilica di Santa Croce is the principal Franciscan church in Florence, Italy, and a minor basilica of the Roman Catholic Church. It is situated on the Piazza di Santa Croce, about 800 meters south-east of the Duomo. The site, when first chosen, was in marshland outside the city walls. It is the burial place of some of the most illustrious Italians, such as Michelangelo, Galileo, Machiavelli, the poet Foscolo, the philosopher Gentile and the composer Rossini, thus it is known also as the Temple of the Italian Glories.");
            landmarkRepository.save(basillica);
            Landmark uffizigallery = new Landmark("Uffizi Gallery", "https://res.cloudinary.com/ivoto22/image/upload/v1635684919/images_8_n55sxe.jpg", florence);
            uffizigallery.setDescription("The Uffizi Gallery is a prominent art museum located adjacent to the Piazza della Signoria in the Historic Centre of Florence in the region of Tuscany, Italy. One of the most important Italian museums and the most visited, it is also one of the largest and best known in the world and holds a collection of priceless works, particularly from the period of the Italian Renaissance. After the ruling House of Medici died out, their art collections were given to the city of Florence under the famous Patto di famiglia negotiated by Anna Maria Luisa, the last Medici heiress. The Uffizi is one of the first modern museums. The gallery had been open to visitors by request since the sixteenth century, and in 1765 it was officially opened to the public, formally becoming a museum in 1865.");
            landmarkRepository.save(uffizigallery);
            Town milano = townService.findByName("Milano");
            Landmark duomo_di_milano = new Landmark("Duomo di Milano", "https://res.cloudinary.com/ivoto22/image/upload/v1635685164/images_9_fzcrsy.jpg", milano);
            duomo_di_milano.setDescription("The Milan Cathedral, or Metropolitan Cathedral-Basilica of the Nativity of Saint Mary, is the cathedral church of Milan, Lombardy, Italy. Dedicated to the Nativity of St Mary, it is the seat of the Archbishop of Milan, currently Archbishop Mario Delpini. The cathedral took nearly six centuries to complete: construction began in 1386, and the final details were completed in 1965. It is the largest church in Italy—the larger St. Peter's Basilica is in the State of Vatican City, a sovereign state—and the second largest in Europe and the third largest in the world.");
            landmarkRepository.save(duomo_di_milano);
            Landmark galleriaemanuelle = new Landmark("Galleria Vittorio Emanuele II", "https://res.cloudinary.com/ivoto22/image/upload/v1635685234/images_10_ljyncs.jpg", milano);
            galleriaemanuelle.setDescription("The Galleria Vittorio Emanuele II is Italy's oldest active shopping gallery and a major landmark of Milan in Italy. Housed within a four-story double arcade in the centre of town, the Galleria is named after Victor Emmanuel II, the first king of the Kingdom of Italy. It was designed in 1861 and built by architect Giuseppe Mengoni between 1865 and 1877.");
            landmarkRepository.save(galleriaemanuelle);
            Town sanmarino = townService.findByName("San Marino");
            Landmark guaitatower = new Landmark("Guaita Tower", "https://res.cloudinary.com/ivoto22/image/upload/v1635685368/images_11_l4nrwp.jpg", sanmarino);
            guaitatower.setDescription("Guaita is one of three peaks which overlooks the city of San Marino, the capital of San Marino. The other two are De La Fratta and Montale.");
            landmarkRepository.save(guaitatower);
            Town vatican = townService.findByName("Vatican");
            Landmark vatcanmuseums = new Landmark("Vatican Museums", "https://res.cloudinary.com/ivoto22/image/upload/v1635691034/images_12_fp226o.jpg", vatican);
            vatcanmuseums.setDescription("The Vatican Museums are the public museums of the Vatican City. They display works from the immense collection amassed by the Catholic Church and the papacy throughout the centuries, including several of the most renowned Roman sculptures and most important masterpieces of Renaissance art in the world. The museums contain roughly 70,000 works, of which 20,000 are on display, and currently employ 640 people who work in 40 different administrative, scholarly, and restoration departments. Pope Julius II founded the museums in the early 16th century. The Sistine Chapel, with its ceiling and altar wall decorated by Michelangelo, and the Stanze di Raffaello are on the visitor route through the Vatican Museums. In 2020, due to the COVID-19 pandemic, the Vatican Museums were visited by only 1,300,000 persons, a drop of 81 percent from the number of visitors in 2019, but still enough to rank the museums fourth among the most-visited art museums in the world. There are 24 galleries, or sale, in total, with the Sistine Chapel, notably, being the last sala within the Museum.");
            landmarkRepository.save(vatcanmuseums);
            Landmark saintpeterssquare = new Landmark("Saint Peter's Square", "https://res.cloudinary.com/ivoto22/image/upload/v1635691114/images_13_hl4eet.jpg", vatican);
            saintpeterssquare.setDescription("Saint Peter's Square is a large plaza located directly in front of St. Peter's Basilica in the Vatican City, the papal enclave inside Rome, directly west of the neighborhood of Borgo. Both the square and the basilica are named after Saint Peter, an apostle of Jesus considered by Catholics to be the first Pope. At the centre of the square is an ancient Egyptian obelisk, erected at the current site in 1586. Gian Lorenzo Bernini designed the square almost 100 years later, including the massive Doric colonnades, four columns deep, which embrace visitors in \"the maternal arms of Mother Church\". A granite fountain constructed by Bernini in 1675 matches another fountain designed by Carlo Maderno in 1613.");
            landmarkRepository.save(saintpeterssquare);
            Town budapest = townService.findByName("Budapest");
            Landmark hungarianparliament = new Landmark("Hungarian Parliament Building", "https://res.cloudinary.com/ivoto22/image/upload/v1635691254/images_14_khpjl2.jpg", budapest);
            hungarianparliament.setDescription("The Hungarian Parliament Building, also known as the Parliament of Budapest after its location, is the seat of the National Assembly of Hungary, a notable landmark of Hungary, and a popular tourist destination in Budapest. It is situated on Kossuth Square in the Pest side of the city, on the eastern bank of the Danube. It was designed by Hungarian architect Imre Steindl in neo-Gothic style and opened in 1902. It has been the largest building in Hungary since its completion.");
            landmarkRepository.save(hungarianparliament);
            Landmark castleVar = new Landmark("Castle Hill (Vár)", "https://res.cloudinary.com/ivoto22/image/upload/v1635691751/Castle-Hill_y0kkfi.jpg", budapest);
            castleVar.setDescription("The winding cobblestone streets and leafy promenades of Castle Hill lead past baroque houses, Habsburg monuments and cafes including early 19th-century Ruszwurm. Key attractions include Buda Castle, a palace razed and rebuilt over centuries, now home to the Hungarian National Gallery and Budapest History Museum. The turrets and terraces of Fisherman’s Bastion offer views over the Danube and nearby Matthias Church");
            landmarkRepository.save(castleVar);
            Landmark citadella = new Landmark("Citadella","https://res.cloudinary.com/ivoto22/image/upload/v1635691887/Citadella_-_Budapest_lrfqmr.jpg", budapest);
            citadella.setDescription("The Citadella is the fortification located upon the top of Gellért Hill in Budapest, Hungary. Citadella is the Hungarian word for citadel, a kind of fortress.");
           landmarkRepository.save(citadella);
            Town vienna = townService.findByName("vienna");
            Landmark schochburnpalace = new Landmark("Schönbrunn Palace", "https://res.cloudinary.com/ivoto22/image/upload/v1635691456/images_15_pi5da3.jpg", vienna);
            schochburnpalace.setDescription("Schönbrunn Palace was the main summer residence of the Habsburg rulers, located in Hietzing, Vienna. The name Schönbrunn has its roots in an artesian well from which water was consumed by the court. The 1,441-room Rococo palace is one of the most important architectural, cultural, and historic monuments in the country. The history of the palace and its vast gardens spans over 300 years, reflecting the changing tastes, interests, and aspirations of successive Habsburg monarchs. It has been a major tourist attraction since the mid-1950s.");
            landmarkRepository.save(schochburnpalace);
            Landmark viennaopera = new Landmark("Vienna State Opera", "https://res.cloudinary.com/ivoto22/image/upload/v1635691529/licensed-image_7_bubdmt.jpg", vienna);
            viennaopera.setDescription("The Vienna State Opera is an opera house and opera company based in Vienna, Austria. The 1,709-seat Renaissance Revival venue was the first major building on the Vienna Ring Road. It was built from 1861 to 1869 following plans by August Sicard von Sicardsburg and Eduard van der Nüll, and designs by Josef Hlávka. The opera house was inaugurated as the \"Vienna Court Opera\" in the presence of Emperor Franz Joseph I and Empress Elisabeth of Austria. It became known by its current name after the establishment of the First Austrian Republic in 1921. The Vienna State Opera is the successor of the Vienna Court Opera, the original construction site chosen and paid for by Emperor Franz Joseph in 1861. The members of the Vienna Philharmonic are recruited from the Vienna State Opera's orchestra. The building is also the home of the Vienna State Ballet, and it hosts the annual Vienna Opera Ball during the carnival season.");
            landmarkRepository.save(viennaopera);
            Landmark prater = new Landmark("Prater", "https://res.cloudinary.com/ivoto22/image/upload/v1635691651/images_16_tfz7ak.jpg", vienna);
            prater.setDescription("The Prater is a large public park in Leopoldstadt, Vienna, Austria. The Wurstelprater, an amusement park that is often simply called \"Prater\", lies in one corner of the Wiener Prater and includes the Wiener Riesenrad Ferris wheel. ");
            landmarkRepository.save(prater);
            Town innsbruck = townService.findByName("Innsbruck");
            Landmark bergisel = new Landmark("Bergisel Ski Jump", "https://res.cloudinary.com/ivoto22/image/upload/v1635694907/licensed-image_8_snwran.jpg", innsbruck);
            bergisel.setDescription("The Bergisel Ski Jump, whose stadium has a capacity of 26,000, is a ski jumping hill located in Bergisel in Innsbruck, Austria. It is one of the more important venues in the FIS Ski Jumping World Cup, annually hosting the third competition of the prestigious Four Hills Tournament. Its first competitions were held in the 1920s using simple wood constructions. The larger hill was first built in 1930 and was rebuilt before the 1964 Winter Olympics for the individual large hill event. Twelve years later, the venue hosted the same event. The hill in its current form was finished in 2003 and was designed by the British Iraqi architect Zaha Hadid.");
            landmarkRepository.save(bergisel);
            Landmark ambrascastle = new Landmark("Ambras Castle", "https://res.cloudinary.com/ivoto22/image/upload/v1635695028/images_17_sllc7z.jpg", innsbruck);
            ambrascastle.setDescription("Ambras Castle is a Renaissance castle and palace located in the hills above Innsbruck, Austria. Ambras Castle is 587 metres above sea level. Considered one of the most popular tourist attractions of the Tyrol, Ambras Castle was built in the 16th century on the spot of an earlier 10th-century castle, which became the seat of power for the Counts of Andechs. The cultural and historical importance of the castle is closely connected with Archduke Ferdinand II and served as his family's residence from 1567 to 1595. Ferdinand was one of history's most prominent collectors of art. The princely sovereign of Tyrol, son of Emperor Ferdinand I, ordered that the medieval fortress at Ambras be turned into a Renaissance castle as a gift for his wife Philippine Welser. The cultured humanist from the House of Habsburg accommodated his world-famous collections in a museum: the collections, still in the Lower Castle built specifically for that museum's purpose, make Castle Ambras Innsbruck one of the oldest museums in the world. The Lower Castle contains armouries that feature masterpieces of the European armourers' art from the time of Emperor Maximilian I to Emperor Leopold I.");
            landmarkRepository.save(ambrascastle);
            Town munich = townService.findByName("Munich");
            Landmark bmwmuseum = new Landmark("BMW Museum", "https://res.cloudinary.com/ivoto22/image/upload/v1635695156/images_18_ywwzln.jpg", munich);
            bmwmuseum.setDescription("The BMW Museum is an automobile museum of BMW history located near the Olympiapark in Munich, Germany. The museum was established in 1973, shortly after the Summer Olympics opened. From 2004 to 2008, it was renovated in connection with the construction of the BMW Welt, directly opposite. The museum reopened on 21 June 2008. At the moment the exhibition space is 5,000 square metres for the presentation of about 120 exhibits.");
            landmarkRepository.save(bmwmuseum);
            Landmark marienplatz = new Landmark("Marienplatz","https://res.cloudinary.com/ivoto22/image/upload/v1635695241/images_19_nyeqnj.jpg", munich);
            marienplatz.setDescription("Marienplatz is a central square in the city centre of Munich, Germany. It has been the city's main square since 1158.");
            landmarkRepository.save(marienplatz);
            Landmark alianzarena = new Landmark("Allianz Arena", "https://res.cloudinary.com/ivoto22/image/upload/v1635695384/images_20_lreltf.jpg", munich);
            alianzarena.setDescription("Allianz Arena is a football stadium in Munich, Bavaria, Germany with a 70,000 seating capacity for international matches and 75,000 for domestic matches. Widely known for its exterior of inflated ETFE plastic panels, it is the first stadium in the world with a full colour changing exterior. Located at 25 Werner-Heisenberg-Allee at the northern edge of Munich's Schwabing-Freimann borough on the Fröttmaning Heath, it is the second-largest arena in Germany behind Westfalenstadion in Dortmund. FC Bayern Munich has played its home games at the Allianz Arena since the start of the 2005–06 season. The club had previously played their home games at the Munich Olympic Stadium since 1972. 1860 Munich previously had a 50% share in the stadium, but Bayern Munich purchased their shares for €11 million in April 2006 due to 1860 Munich suffering from financial issues. The arrangement allowed 1860 Munich to play at the stadium while retaining no ownership until 2025. However, in July 2017 Bayern terminated the rental contract with 1860, making themselves the sole tenants of the stadium.");
            landmarkRepository.save(alianzarena);
            Landmark oldtownhall = new Landmark("Old Town Hall", "https://res.cloudinary.com/ivoto22/image/upload/v1635695522/images_21_yvvtlh.jpg", munich);
            oldtownhall.setDescription("The Old Town Hall, until 1874 the domicile of the municipality, serves today as a building for representative purposes for the city council in Munich. The Old Town Hall bounds the central square Marienplatz on its east side.");
            landmarkRepository.save(oldtownhall);
            Town frankfurt = townService.findByName("Frankfurt");
            Landmark goethehouse = new Landmark("Goethe House", "https://res.cloudinary.com/ivoto22/image/upload/v1635695673/images_22_zlf8ah.jpg", frankfurt);
            goethehouse.setDescription("The Goethe House is a writer's house museum in the Innenstadt district of Frankfurt am Main, Germany. It is a birthplace of Johann Wolfgang von Goethe. Decorated with period furniture and paintings, it provides an authentic environment in which Goethe spent his youth. It is also a place where Goethe wrote his famous works Götz von Berlichingen, Faust and The Sorrows of Young Werther.");
            landmarkRepository.save(goethehouse);
            Landmark frankfurtcathedral = new Landmark("Frankfurt Cathedral", "https://res.cloudinary.com/ivoto22/image/upload/v1635695943/images_23_nedw4c.jpg", frankfurt);
            frankfurtcathedral.setDescription("Frankfurt Cathedral, officially Imperial Cathedral of Saint Bartholomew is a Roman Catholic Gothic church located in the centre of Frankfurt am Main, Germany. It is dedicated to Saint Bartholomew. It is the largest religious building in the city and a former collegiate church. Despite its common English name, it has never been a true cathedral, but is called the Kaiserdom or simply the Dom due to its importance as former election and coronation church of the Holy Roman Empire. As one of the major buildings of the Empire's history, it was a symbol of national unity, especially in the 19th century. The present church building is the third church on the same site. Since the late 19th century, excavations have revealed buildings that can be traced back to the 7th century. The history is closely linked with the general history of Frankfurt and Frankfurt's old town because the cathedral had an associated role as the religious counterpart of the Royal Palace in Frankfurt.");
            landmarkRepository.save(frankfurtcathedral);
            Town stuttgart = townService.findByName("Stuttgart");
            Landmark mercedesmuseum = new Landmark("Mercedes-Benz Museum", "https://res.cloudinary.com/ivoto22/image/upload/v1635696186/images_24_ajvigp.jpg", stuttgart);
            mercedesmuseum.setDescription("The Mercedes-Benz Museum is an automobile museum in Stuttgart, Germany. It covers the history of the Mercedes-Benz brand and the brands associated with it. Stuttgart is home to the Mercedes-Benz brand and the international headquarters of Daimler AG.");
            landmarkRepository.save(mercedesmuseum);
            Landmark proschemuseum = new Landmark("Porsche Museum", "https://res.cloudinary.com/ivoto22/image/upload/v1635701834/images_25_xewoyq.jpg", stuttgart);
            proschemuseum.setDescription("The Porsche Museum is an automobile museum in the Zuffenhausen district of Stuttgart, Germany on the site of carmaker Porsche.");
            landmarkRepository.save(proschemuseum);
            Town rust = townService.findByName("Rust");
            Landmark europapark = new Landmark("Europa Park", "https://res.cloudinary.com/ivoto22/image/upload/v1635701972/panorama_europa-park_onaqtz.jpg", rust);
            europapark.setDescription("Europa-Park is the largest theme park in Germany, and the second most popular theme park in Europe, after Disneyland Paris.[1] Europa-Park is located in Rust, south-western Germany, between Freiburg im Breisgau and Strasbourg (in neighbouring France).[2]" +
                    "The park is home to 13 roller coasters, the oldest, which opened in 1984, is the Alpenexpress Enzian, which is a powered coaster that speeds through a diamond mine. Europa-Park has very high capacity roller coasters and attractions, meaning the park can accommodate approximately 60,000 guests per day.[3] The park counted 5.75 million visitors in 2019.[4] It is also the location of the Euro Dance Festival." +
                    "The resort (park, parking lot, hotels and back stages) occupies roughly 95 hectares. It hosts six hotels, one campground, and one movie theater." +
                    "In November 2019, Europa-Park's \"Rulantica\" water park opened, along with the Museum-Themed Hotel, \"Krønasår\".");
            landmarkRepository.save(europapark);
            Town paris = townService.findByName("Paris");
            Landmark eiffeltower = new Landmark("Eiffel Tower", "https://res.cloudinary.com/ivoto22/image/upload/v1635706609/licensed-image_9_mw6qp8.jpg", paris);
            eiffeltower.setDescription("The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. Locally nicknamed \"La dame de fer\", it was constructed from 1887 to 1889 as the entrance to the 1889 World's Fair and was initially criticised by some of France's leading artists and intellectuals for its design, but it has become a global cultural icon of France and one of the most recognisable structures in the world. The Eiffel Tower is the most visited monument with an entrance fee in the world; 6.91 million people ascended it in 2015. The tower is 324 metres tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is square, measuring 125 metres on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become the tallest man-made structure in the world, a title it held for 41 years until the Chrysler Building in New York City was finished in 1930. It was the first structure in the world to surpass both the 200-metre and 300-metre mark in height.");
            landmarkRepository.save(eiffeltower);
            Landmark disneyland = new Landmark("Disneyland", "https://res.cloudinary.com/ivoto22/image/upload/v1635759933/download_s5keqo.jpg", paris);
            disneyland.setDescription("Disneyland Paris, formerly Euro Disney Resort, is an entertainment resort in Chessy, France, a town located 32 km east of the centre of Paris.");
            landmarkRepository.save(disneyland);
            Landmark louvre = new Landmark("Louvre Museum", "https://res.cloudinary.com/ivoto22/image/upload/v1635760062/images_26_aqvyok.jpg", paris);
            louvre.setDescription("The Louvre, or the Louvre Museum, is the world's most-visited museum and a historic monument in Paris, France. It is the home of many of the most known work of arts, including the Mona Lisa. A central landmark of the city, it is located on the Right Bank of the Seine in the city's 1st arrondissement. Approximately 38,000 objects from prehistory to the 21st century are exhibited over an area of 72,735 square meters. Due to the COVID-19 pandemic, the museum was closed for 150 days in 2020, and attendance plunged by 72 percent to 2.7 million. Nonetheless, the Louvre still topped the list of most-visited art museums in the world in 2020. The museum is housed in the Louvre Palace, originally built in the late 12th to 13th century under Philip II. Remnants of the Medieval Louvre fortress are visible in the basement of the museum. Due to urban expansion, the fortress eventually lost its defensive function, and in 1546 Francis I converted it into the primary residence of the French Kings. The building was extended many times to form the present Louvre Palace.");
            landmarkRepository.save(louvre);
            Landmark arcdetrioumf = new Landmark("Arc de Triomphe", "https://res.cloudinary.com/ivoto22/image/upload/v1635760130/images_27_dkbz8f.jpg",paris);
            arcdetrioumf.setDescription("The Arc de Triomphe de l'Étoile is one of the most famous monuments in Paris, France, standing at the western end of the Champs-Élysées at the centre of Place Charles de Gaulle, formerly named Place de l'Étoile—the étoile or \"star\" of the juncture formed by its twelve radiating avenues. The location of the arc and the plaza is shared between three arrondissements, 16th, 17th, and 8th. The Arc de Triomphe honours those who fought and died for France in the French Revolutionary and Napoleonic Wars, with the names of all French victories and generals inscribed on its inner and outer surfaces. Beneath its vault lies the Tomb of the Unknown Soldier from World War I. As the central cohesive element of the Axe historique, the Arc de Triomphe was designed by Jean Chalgrin in 1806; its iconographic programme pits heroically nude French youths against bearded Germanic warriors in chain mail. It set the tone for public monuments with triumphant patriotic messages. Inspired by the Arch of Titus in Rome, Italy, the Arc de Triomphe has an overall height of 50 metres, width of 45 m and depth of 22 m, while its large vault is 29.19 m high and 14.62 m wide.");
            landmarkRepository.save(arcdetrioumf);
            Town strassbourg = townService.findByName("Strasbourg");
            Landmark notredamedistrassbourg = new Landmark("Cathédrale Notre Dame de Strasbourg", "https://res.cloudinary.com/ivoto22/image/upload/v1635760343/images_28_ah20sr.jpg", strassbourg);
            notredamedistrassbourg.setDescription("Strasbourg Cathedral or the Cathedral of Our Lady of Strasbourg, also known as Strasbourg Minster, is a Catholic cathedral in Strasbourg, Alsace, France. Although considerable parts of it are still in Romanesque architecture, it is widely considered to be among the finest examples of Rayonnant Gothic architecture. Architect Erwin von Steinbach is credited for major contributions from 1277 to his death in 1318, and beyond through his son Johannes von Steinbach, and his grandson Gerlach von Steinbach, who succeeded him as chief architects. The Steinbachs's plans for the completion of the cathedral were not followed through by the chief architects who took over after them, and instead of the originally envisioned two spires, a single, octagonal tower with an elongated, octagonal crowning was built on the northern side of the west facade by master Ulrich von Ensingen and his successor, Johannes Hültz. The construction of the cathedral, which had started in the year 1015 and had been relaunched in 1190, was finished in 1439. At 142 metres, Strasbourg Cathedral was the world's tallest building from 1647 to 1874, when it was surpassed by St. Nikolai's Church, Hamburg.");
            landmarkRepository.save(notredamedistrassbourg);
            Landmark couverts = new Landmark("Ponts Couverts de Strasbourg", "https://res.cloudinary.com/ivoto22/image/upload/v1635760454/licensed-image_10_u6nkub.jpg", strassbourg);
            couverts.setDescription("The Ponts Couverts are a set of three bridges and four towers that make up a defensive work erected in the 13th century on the River Ill in the city of Strasbourg in France. The three bridges cross the four river channels of the River Ill that flow through Strasbourg's historic Petite France quarter. The Ponts Couverts have been classified as a Monument historique since 1928. Construction of the Ponts Couverts commenced in 1230, and they were opened in 1250. As a defensive mechanism, they were superseded by the Barrage Vauban, just upstream, in 1690, but remained in use as bridges. As built, each of the bridges was covered by a wooden roof that served to protect the defenders who would have been stationed on them in time of war. These roofs were removed in 1784, but name Ponts Couverts has remained in common use ever since.");
            landmarkRepository.save(couverts);
            Town lyon = townService.findByName("Lyon");
            Landmark palacedebour = new Landmark("Place Bellecour", "https://res.cloudinary.com/ivoto22/image/upload/v1635760665/licensed-image_11_guxel6.jpg", lyon);
            palacedebour.setDescription("La Place Bellecour is a large square in the centre of Lyon, France, to the north of the Ainay district. Measuring 312 m by 200 m, it is one of the largest open squares in Europe, and the third biggest square in France, behind the Place des Quinconces in Bordeaux and the Place de la Concorde in Paris. It is also the largest pedestrian square in Europe: vehicles are allowed in Places de la Concorde and des Quinconces. In the middle is an equestrian statue of king Louis XIV by François-Frédéric Lemot. Another statue, representing the Petit Prince and Antoine de Saint-Exupéry, is at the west end of the square. The square also has two pavilions, housing the tourist information office of Lyon and an art gallery. The square is part of a UNESCO World Heritage Site.");
            landmarkRepository.save(palacedebour);
            Town andorra = townService.findByName("Andorra la Vella");
            Landmark andorramountain = new Landmark("Grandvalira","https://res.cloudinary.com/ivoto22/image/upload/v1635760879/licensed-image_12_lvocvz.jpg", andorra);
            andorramountain.setDescription("Mountain resort for skiing & zip lining");
            landmarkRepository.save(andorramountain);
            Landmark mirador = new Landmark("Mirador Roc Del Quer", "https://res.cloudinary.com/ivoto22/image/upload/v1635770805/licensed-image_13_es1yzl.jpg", andorra);
            mirador.setDescription("Lookout with views over alpine valleys");
            landmarkRepository.save(mirador);
            Town madrid = townService.findByName("Madrid");
            Landmark royalpalaceofmadrid = new Landmark("Royal Palace of Madrid", "https://res.cloudinary.com/ivoto22/image/upload/v1635770898/images_29_tdokq6.jpg", madrid);
            royalpalaceofmadrid.setDescription("The Royal Palace of Madrid is the official residence of the Spanish royal family at the city of Madrid, although now used only for state ceremonies. The palace has 135,000 m² of floor space and contains 3,418 rooms. It is the largest functioning royal palace and the largest by floor area in Europe. King Felipe VI and the royal family do not reside in the palace, choosing instead the significantly more modest Palace of Zarzuela on the outskirts of Madrid. The palace is now open to the public, except during state functions, although it is so large that only a selection of the best rooms are on the visitor route at any one time, the route being changed every few months. An admission fee of €13 is charged; however, at some times it is free. The palace is owned by the Spanish state and administered by the Patrimonio Nacional, a public agency of the Ministry of the Presidency. The palace is on Calle de Bailén in the western part of downtown Madrid, east of the Manzanares River, and is accessible from the Ópera metro station.");
            landmarkRepository.save(royalpalaceofmadrid);
            Landmark templeofdaboud = new Landmark("Temple of Debod", "https://res.cloudinary.com/ivoto22/image/upload/v1635770964/images_30_id0srp.jpg", madrid);
            templeofdaboud.setDescription("The Temple of Debod is an ancient Egyptian temple that was dismantled and rebuilt in the center of Madrid, Spain, in Parque de la Montaña, Madrid, a square located Calle de Irún, 21–25 Madrid.");
            landmarkRepository.save(templeofdaboud);
            Town barcelona = townService.findByName("Barcelona");
            Landmark lasgradafamilia = new Landmark("La Sagrada Familia","https://res.cloudinary.com/ivoto22/image/upload/v1635771071/licensed-image_14_e4hjrt.jpg", barcelona);
            lasgradafamilia.setDescription("The Basílica de la Sagrada Família, also known as the Sagrada Família, is a large unfinished minor basilica in the Eixample district of Barcelona, Catalonia, Spain. Designed by the Spanish architect Antoni Gaudí, his work on the building is part of a UNESCO World Heritage Site. On 7 November 2010, Pope Benedict XVI consecrated the church and proclaimed it a minor basilica. On 19 March 1882, construction of the Sagrada Família began under architect Francisco de Paula del Villar. In 1883, when Villar resigned, Gaudí took over as chief architect, transforming the project with his architectural and engineering style, combining Gothic and curvilinear Art Nouveau forms. Gaudí devoted the remainder of his life to the project, and he is buried in the crypt. At the time of his death in 1926, less than a quarter of the project was complete. Relying solely on private donations, the Sagrada Família's construction progressed slowly and was interrupted by the Spanish Civil War.");
            landmarkRepository.save(lasgradafamilia);
            Landmark cathedralofbarcelona = new Landmark("Cathedral of Barcelona","https://res.cloudinary.com/ivoto22/image/upload/v1635771154/images_31_mntjii.jpg", barcelona);
            cathedralofbarcelona.setDescription("The Cathedral of the Holy Cross and Saint Eulalia, also known as Barcelona Cathedral, is the Gothic cathedral and seat of the Archbishop of Barcelona, Catalonia, Spain. The cathedral was constructed from the thirteenth to fifteenth centuries, with the principal work done in the fourteenth century. The cloister, which encloses the Well of the Geese was completed in 1448. In the late nineteenth century, the neo-Gothic façade was constructed over the nondescript exterior that was common to Catalan churches. The roof is notable for its gargoyles, featuring a wide range of animals, both domestic and mythical. Its form is pseudo-basilica, vaulted over five aisles, the outer two divided into chapels. The transept is truncated. The east end is a chevet of nine radiating chapels connected by an ambulatory. The high altar is raised, allowing a clear view into the crypt. The cathedral is dedicated to Eulalia of Barcelona, co-patron saint of Barcelona, a young virgin who, according to Catholic tradition, suffered martyrdom during Roman times in the city. One story says that she was exposed naked in the public square and a miraculous snowfall in mid-spring covered her nudity.");
            landmarkRepository.save(cathedralofbarcelona);
            Landmark campnou = new Landmark("Camp Nou","https://res.cloudinary.com/ivoto22/image/upload/v1635771248/download_1_dgr3tf.jpg",barcelona);
            campnou.setDescription("Camp Nou is a football stadium in Barcelona, Spain. It opened in 1957 and has been the home stadium of FC Barcelona since its completion. With a seating capacity of 99,354, it is the largest stadium in Spain and Europe, and the fourth largest association football stadium in the world in capacity.");
            landmarkRepository.save(campnou);
            Town seville = townService.findByName("Seville");
            Landmark plazadeespana = new Landmark("Plaza de España", "https://res.cloudinary.com/ivoto22/image/upload/v1635771460/images_32_rkk6pg.jpg", seville);
            plazadeespana.setDescription("The Plaza de España is a plaza in the Parque de María Luisa, in Seville, Spain. It was built in 1928 for the Ibero-American Exposition of 1929. It is a landmark example of Regionalism Architecture, mixing elements of the Baroque Revival, Renaissance Revival and Moorish Revival styles of Spanish architecture.");
            landmarkRepository.save(plazadeespana);
            Town lisbon = townService.findByName("Lisbon");
            Landmark castelodesaintjorge = new Landmark("Castelo de S. Jorge","https://res.cloudinary.com/ivoto22/image/upload/v1635771536/images_33_pka63d.jpg", lisbon);
            castelodesaintjorge.setDescription("São Jorge Castle is a historic castle in the Portuguese capital of Lisbon, located in the freguesia of Santa Maria Maior. Human occupation of the castle hill dates to at least the 8th century BC while the first fortifications built date from the 1st century BC. The hill on which São Jorge Castle stands has played an important part in the history of Lisbon, having served as the location of fortifications occupied successively by Phoenicians, Carthaginians, Romans, and Moors, before its conquest by the Portuguese in the 1147 Siege of Lisbon. Since the 12th century, the castle has variously served as a royal palace, a military barracks, home of the Torre do Tombo National Archive, and now as a national monument and museum.");
            landmarkRepository.save(castelodesaintjorge);
            Landmark praca = new Landmark("Praça do Comércio","https://res.cloudinary.com/ivoto22/image/upload/v1635771620/images_34_blpkpb.jpg", lisbon);
            praca.setDescription("The Praça do Comércio is a large, harbour-facing square in Portugal's capital, Lisbon, being one of the largest in Portugal, with 175 by 175 m, that is, 30,600 m². Facing the Tagus to the South, the city square is still commonly known in Portuguese as Terreiro do Paço, as it hosted the Paço da Ribeira until it was destroyed by the great 1755 Lisbon earthquake. After the earthquake, the square was completely remodeled as part of the rebuilding of the Pombaline Downtown, ordered by Sebastião José de Carvalho e Melo, 1st Marquis of Pombal, who was Minister of Portugal from 1750 to 1777, during the reign of the Portuguese King José I. From the 19th century onwards, Praça do Comércio became the seat of some of the most important Portuguese state departaments, including the Ministries of Finances, Internal Affairs, Agriculture and Sea; before the Carnation Revolution and the creation of a unified Ministry of Defence, it was also the location of the War and Navy Ministries, as well as the old Ministry of Colonies, thus becoming a methonym for the Portuguese central government. Furthermore, the Supreme Court is also housed there.");
            landmarkRepository.save(praca);
            Town porto = townService.findByName("Porto");
            Landmark luisbridge = new Landmark("Luís I Bridge", "https://res.cloudinary.com/ivoto22/image/upload/v1635776399/images_35_iyfb1t.jpg", porto);
            luisbridge.setDescription("The Dom Luís I Bridge, or Luís I Bridge, is a double-deck metal arch bridge that spans the River Douro between the cities of Porto and Vila Nova de Gaia in Portugal. At its construction, its 172 metres span was the longest of its type in the world. It has been confused with the nearby Maria Pia Bridge, a railway bridge that was built 9 years earlier, which is similar in aspect to the Luís I bridge.");
            landmarkRepository.save(luisbridge);
            Town male = townService.findByName("Male");
            Landmark huhlmale = new Landmark("Hulhumale","https://res.cloudinary.com/ivoto22/image/upload/v1635776676/images_36_xlu91d.jpg", male);
            huhlmale.setDescription("Hulhumalé is a reclaimed island located in the south of North Malé Atoll, Maldives. The artificial island is being built up by pumping sand from the sea floor, in order to meet the existing and future housing, industrial and commercial development demands of the Malé region and as a response to the threat posed by rising sea levels. The official settlement was inaugurated by President Maumoon Abdul Gayoom on May 12, 2004. The development and management of the island is undertaken by a government-owned corporation called Housing Development Corporation which was incorporated on March 23, 2005. Land reclamation has increased the island's area to 4 km², making it the fourth largest island in the Maldives. As of December 2019 the island has a population of more than 50,000; it is planned to house as many as 240,000 by the mid-2020s");
            landmarkRepository.save(huhlmale);
            Town istanbul = townService.findByName("Istanbul");
            Landmark hagiasophia = new Landmark("Hagia Sophia","https://res.cloudinary.com/ivoto22/image/upload/v1635776841/images_37_ezfs5a.jpg", istanbul);
            hagiasophia.setDescription("Hagia Sophia, officially the Holy Hagia Sophia Grand Mosque, and formerly the Church of Hagia Sophia, is a Late Antique place of worship in Istanbul, designed by the Greek geometers Isidore of Miletus and Anthemius of Tralles. Built in 537 as the patriarchal cathedral of the imperial capital of Constantinople, it was the largest Christian church of the eastern Roman Empire and the Eastern Orthodox Church, except during the Latin Empire from 1204 to 1261, when it became the city's Latin Catholic cathedral. In 1453, after the Fall of Constantinople to the Ottoman Empire, it was converted into a mosque. In 1935, the secular Turkish Republic established it as a museum. In 2020, it re-opened as a mosque. Built by the eastern Roman emperor Justinian I as the Christian cathedral of Constantinople for the state church of the Roman Empire between 532 and 537, the church was then the world's largest interior space and among the first to employ a fully pendentive dome. It is considered the epitome of Byzantine architecture and is said to have \"changed the history of architecture\"");
            landmarkRepository.save(hagiasophia);
            Landmark bosphorus = new Landmark("Bosphorus", "https://res.cloudinary.com/ivoto22/image/upload/v1635776928/images_38_y3uquj.jpg", istanbul);
            bosphorus.setDescription("The Bosporus or Bosphorus, also known as the Strait of Istanbul, is a narrow, natural strait and an internationally significant waterway located in northwestern Turkey. It forms part of the continental boundary between Europe and Asia, and divides Turkey by separating Anatolia from Thrace. It is the world's narrowest strait used for international navigation. The Bosporus connects the Black Sea with the Sea of Marmara, and, by extension via the Dardanelles, the Aegean and Mediterranean seas, and by the Kerch Strait, the sea of Azov. Most of the shores of the strait, except for those in the north, are heavily settled, straddled by the city of Istanbul's metropolitan population of 17 million inhabitants extending inland from both coasts. Together with the Dardanelles, the Bosporus forms the Turkish Straits.");
            landmarkRepository.save(bosphorus);
            Town london = townService.findByName("London");
            Landmark londoneye = new Landmark("London Eye", "https://res.cloudinary.com/ivoto22/image/upload/v1635777099/images_39_lirrbs.jpg", london);
            londoneye.setDescription("The London Eye, or the Millennium Wheel, is a cantilevered observation wheel on the South Bank of the River Thames in London. It is Europe's tallest cantilevered observation wheel, and is the most popular paid tourist attraction in the United Kingdom with over 3 million visitors annually. It has made many appearances in popular culture. The structure is 135 metres tall and the wheel has a diameter of 120 metres. When it opened to the public in 2000 it was the world's tallest Ferris wheel. Its height was surpassed by the 160 metres Star of Nanchang in 2006, the 165 metres Singapore Flyer in 2008, and the 167 metres High Roller in 2014. Supported by an A-frame on one side only, unlike the taller Nanchang and Singapore wheels, the Eye is described by its operators as \"the world's tallest cantilevered observation wheel\". The London Eye used to offer the highest public viewing point in London until it was superseded by the 245-metre-high observation deck on the 72nd floor of The Shard, which opened to the public on 1 February 2013.");
            landmarkRepository.save(londoneye);
            Landmark toweroflondon = new Landmark("Tower of London","https://res.cloudinary.com/ivoto22/image/upload/v1635777405/images_40_vdxbi8.jpg",london);
            toweroflondon.setDescription("The Tower of London, officially Her Majesty's Royal Palace and Fortress of the Tower of London, is a historic castle on the north bank of the River Thames in central London. It lies within the London Borough of Tower Hamlets, which is separated from the eastern edge of the square mile of the City of London by the open space known as Tower Hill. It was founded towards the end of 1066 as part of the Norman Conquest. The White Tower, which gives the entire castle its name, was built by William the Conqueror in 1078 and was a resented symbol of oppression, inflicted upon London by the new ruling elite. The castle was also used as a prison from 1100 until 1952, although that was not its primary purpose. A grand palace early in its history, it served as a royal residence. As a whole, the Tower is a complex of several buildings set within two concentric rings of defensive walls and a moat. There were several phases of expansion, mainly under kings Richard I, Henry III, and Edward I in the 12th and 13th centuries. The general layout established by the late 13th century remains despite later activity on the site. The Tower of London has played a prominent role in English history.");
            landmarkRepository.save(toweroflondon);
            Landmark bigben = new Landmark("Big Ben","https://res.cloudinary.com/ivoto22/image/upload/v1635777532/15547049-the-big-ben-the-houses-of-parliament-and-westminster-bridge-in-london_g7h8gw.jpg", london);
            bigben.setDescription("Big Ben is the nickname for the Great Bell of the striking clock at the north end of the Palace of Westminster, although the name is frequently extended to refer also to the clock and the clock tower.");
            landmarkRepository.save(bigben);








        }

    }

    @Override
    public void createLandmark(LandmarkServiceModel landmarkServiceModel) {
        Landmark landmark = modelMapper.map(landmarkServiceModel,Landmark.class);
        landmarkRepository.save(landmark);
    }

    @Override
    public Landmark findById(Long id) {
        return landmarkRepository.findById(id).orElse(null);
    }

    @Override
    public void editLandmark(Long id, LandmarkServiceModel landmarkServiceModel) {
        Landmark landmark = findById(id);
        landmark.setDescription(landmarkServiceModel.getDescription());
        landmark.setName(landmarkServiceModel.getName());
        landmark.setPictureURL(landmarkServiceModel.getPictureURL());
        landmarkRepository.save(landmark);
    }

    @Override
    public Long getTownId(Long id) {
        return findById(id).getTown().getId();
    }

    @Override
    public void deleteLandmark(Long id) {
        landmarkRepository.deleteById(id);
    }
}
